apiVersion: v1
kind: Pod
metadata:
  labels:
    run: temp-pod2-again
  name: temp-pod2-again
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                  - bottlerocket-nvidia
                  - bottlerocket-arm64-nvidia
  containers:
    - image: nvidia/cuda:13.0.2-base-ubuntu24.04
      name: cuda-sample
      resources:
        limits:
          nvidia.com/gpu: 1
      command:
        - "sh"
        - "-c"
        - "while true; do sleep 6000; done"
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    - key: kubernetes.io/arch
      operator: Equal
      value: "arm64"
