apiVersion: v1
kind: Pod
metadata:
  labels:
    run: temp-pod2
  name: temp-pod2
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                  - bottlerocket-nvida
  containers:
    - image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0
      name: cuda-sample
      resources:
        limits:
          nvidia.com/gpu: 1
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
