apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shmtest
  name: shmtest
  namespace: default
spec:
  containers:
    - image: python:3-alpine
      name: pythona
      command:
        - "sh"
        - "-c"
        - "while true; do sleep 6000; done"
      volumeMounts:
        - mountPath: /dev/shm
          name: shmem
    - name: pythonb
      image: python:3-alpine
      command:
        - "sh"
        - "-c"
        - "while true; do sleep 6000; done"
      volumeMounts:
        - mountPath: /dev/shm
          name: shmem
  volumes:
    - name: shmem
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
    - key: kubernetes.io/arch
      operator: Equal
      value: "arm64"
