apiVersion: v1
kind: Pod
metadata:
  labels:
    run: temp-pod2
  name: temp-pod2
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                  - metal
  containers:
    - image: qemux/qemu
      name: qemu
      env:
        - name: BOOT
          value: ubuntus
      ports:
        - containerPort: 8006
          name: http
          protocol: TCP
        - containerPort: 5900
          name: vnc
          protocol: TCP
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
        privileged: true
      volumeMounts:
        - mountPath: /dev/kvm
          name: dev-kvm
        - mountPath: /dev/net/tun
          name: dev-tun
        - mountPath: /dev/shm
          name: shmem
    - name: busybox
      image: busybox:1.30.1
      command:
        - "sh"
        - "-c"
        - "while true; do sleep 6000; done"
      volumeMounts:
        - mountPath: /dev/shm
          name: shmem
  volumes:
    - hostPath:
        path: /dev/kvm
      name: dev-kvm
    - hostPath:
        path: /dev/net/tun
        type: CharDevice
      name: dev-tun
    - name: shmem
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
    - effect: NoSchedule
      key: bare-metal
      operator: Exists
    - key: kubernetes.io/arch
      operator: Equal
      value: "arm"
